package com.sample.rules;
unit MsgRuleUnit;
import com.sample.model.*;
query message $m : /messages end

rule "Hello World"
	when
		m: /messages[status == Message.HELLO, myMessage : message]
	then
		System.out.println(myMessage);
		m.setMessage("Goodbye cruel world");
		m.setStatus(Message.GOODBYE);
		update(m);
end

rule "GoodBye"
	when
		/messages[status == Message.GOODBYE, myMessage : message]
	then
		System.out.println(myMessage);
end


